title: rarira
description: studio that challenges both web and mobile app

url: http://rarira.github.io
baseurl: ''
paginate_path: 'blog/page:num/'
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: rarira
  twitter: rarira
  # facebook: brianmaierjr
  email: rariradev@gmail.com

google_analytics: ''
